CREATE SCHEMA IF NOT EXISTS MANAGEMENT;
SET SCHEMA MANAGEMENT;

DROP TABLE IF EXISTS CAR_BOOKING;
DROP TABLE IF EXISTS CAR_PICKUP;

CREATE TABLE CAR_BOOKING
(
    VIN            CHAR(17) NOT NULL,
    BOOKING_NUMBER INTEGER  NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY (BOOKING_NUMBER)
);

CREATE TABLE CAR_PICKUP
(
    BOOKING_NUMBER     INTEGER     NOT NULL,
    DRIVER_FIRSTNAME   VARCHAR(50) NOT NULL,
    DRIVER_LASTNAME    VARCHAR(50) NOT NULL,
    DRIVER_LICENCE     VARCHAR(50) NOT NULL,
    PICKUP_TIME        TIMESTAMP   NOT NULL,
    CAR_STATE_FUEL     TINYINT     NOT NULL,
    CAR_STATE_ODOMETER INTEGER     NOT NULL,
    CONSTRAINT CAR_PICKUP_PK PRIMARY KEY (BOOKING_NUMBER)
);

INSERT INTO CAR_BOOKING (BOOKING_NUMBER, VIN)
VALUES (1, 'WMEEJ8AA3FK792135'),
       (2, 'WMEEJ8AA3FK792135');

