CREATE SCHEMA IF NOT EXISTS MANAGEMENT;
SET SCHEMA MANAGEMENT;

DROP TABLE IF EXISTS CAR_BOOKING;

CREATE TABLE CAR_BOOKING
(
    VIN            CHAR(17) NOT NULL,
    BOOKING_NUMBER INTEGER  NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY (BOOKING_NUMBER)
);

INSERT INTO CAR_BOOKING (BOOKING_NUMBER, VIN)
VALUES (1, 'WMEEJ8AA3FK792135'),
       (2, 'WMEEJ8AA3FK792135');

