CREATE SCHEMA IF NOT EXISTS MANAGEMENT;
SET SCHEMA MANAGEMENT;

DROP TABLE IF EXISTS CAR_BOOKINGS;


CREATE TABLE CAR_BOOKINGS
(
    VIN              CHAR(17)       NOT NULL,
    BOOKING_NUMBER   INTEGER        NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY (VIN)
);

COMMIT;

